/* Build a TEKS code -> IXL skill map from IXL's published Texas alignment pages.

   IXL nests its alignment pages in the same shape as the TEKS itself:

     LI.each-category   "2 Listening, speaking, reading, writing..."   <- strand
       LI.each-category   "A demonstrate and apply phonetic knowledge" <- expectation letter
         LI.each-category   "i decoding words with..."                 <- roman sub-item
           A.skillLink   -> the IXL skill

   so a guide that already cites 4.2.A can be routed to practice with no
   keyword guessing. The pages are client-rendered, so this needs a browser.

   Run:  node tools/fetch-ixl.js [--grades K,1,2] [--subjects ela,math]
   Out:  data/ixl-map.js   (window.IXL = { "ELAR|4.2.A": [ {u,n,c}, ... ] })

   NOTE: writing the map does not put IXL in front of students. Rendering is a
   separate step, and IXL practice needs a school licence: signed out, students
   get a few questions then a paywall.
*/
const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const argVal = (flag, dflt) => {
  const i = args.indexOf(flag);
  return i > -1 && args[i + 1] ? args[i + 1] : dflt;
};
const GRADES = argVal('--grades', 'K,1,2,3,4,5,6,7,8').split(',');
const SUBJECTS = argVal('--subjects', 'ela,math').split(',');
const OUT = path.join(__dirname, '..', 'data', 'ixl-map.js');

// IXL uses "kindergarten" in its URLs; the kiosk uses "K".
const slugFor = g => (g === 'K' ? 'kindergarten' : 'grade-' + g);
const prefixFor = subj => (subj === 'math' ? 'MATH' : 'ELAR');

async function scrape(page, subject, grade) {
  const url = `https://www.ixl.com/standards/texas/${subject}/${slugFor(grade)}`;
  await page.goto(url, { waitUntil: 'networkidle', timeout: 90000 });
  await page.waitForTimeout(2500);

  return page.evaluate(() => {
    // leading token of a category label: "2 Listening..." -> "2", "A demo..." -> "A"
    const lead = li => {
      const own = (li.childNodes ? Array.from(li.childNodes) : [])
        .filter(n => n.nodeType === 3 || (n.nodeType === 1 && !/^(UL|OL)$/.test(n.tagName)))
        .map(n => (n.textContent || '').trim()).join(' ').trim();
      const m = own.match(/^\(?([0-9]{1,2}|[A-Z])\)?[\s.)]/);
      return m ? m[1] : null;
    };

    const rows = [];
    document.querySelectorAll('a.skillLink').forEach(a => {
      const parts = [];
      let el = a.parentElement;
      while (el) {
        if (el.tagName === 'LI' && el.classList.contains('each-category')) {
          const t = lead(el);
          if (t) parts.unshift(t);
        }
        el = el.parentElement;
      }
      // keep strand + letter only; roman sub-items are finer than TEKS codes
      const strand = parts.find(x => /^[0-9]+$/.test(x));
      const letter = parts.find(x => /^[A-Z]$/.test(x));
      if (!strand) return;
      rows.push({
        strand, letter: letter || null,
        u: 'https://www.ixl.com' + a.getAttribute('href'),
        n: (a.querySelector('.standard-skill-name') || a).innerText.trim().replace(/\s+/g, ' '),
        c: (a.querySelector('.standard-skill-code') || {}).innerText || ''
      });
    });
    return rows;
  });
}

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1280, height: 1200 } });
  const map = {};
  let total = 0;

  for (const subject of SUBJECTS) {
    for (const grade of GRADES) {
      let rows = [];
      try {
        rows = await scrape(page, subject, grade);
      } catch (e) {
        console.log(`  ${subject} ${grade}: FAILED ${String(e.message).slice(0, 60)}`);
        continue;
      }
      const pfx = prefixFor(subject);
      let added = 0;
      for (const r of rows) {
        const code = `${pfx}|${grade}.${r.strand}` + (r.letter ? '.' + r.letter : '');
        (map[code] = map[code] || []).push({ u: r.u, n: r.n, c: (r.c || '').trim() });
        added++;
      }
      total += added;
      console.log(`  ${subject.padEnd(4)} ${String(grade).padEnd(2)}  ${String(rows.length).padStart(4)} skills -> ${added} pairs`);
    }
  }

  // de-duplicate per code, keep order
  for (const k of Object.keys(map)) {
    const seen = new Set();
    map[k] = map[k].filter(s => (seen.has(s.u) ? false : seen.add(s.u)));
  }

  const header = `/* Auto-generated by tools/fetch-ixl.js from IXL's published Texas
   alignment pages. Do not hand-edit: re-run the tool.
   Keyed by the same TEKS codes the guides already cite. */\n`;
  fs.writeFileSync(OUT, header + 'window.IXL = ' + JSON.stringify(map) + ';\n', 'utf8');
  console.log(`\nwrote ${path.relative(path.join(__dirname, '..'), OUT)}: ` +
    `${Object.keys(map).length} TEKS codes, ${total} skill links`);
  await browser.close();
})();
